backend:
  name: git-gateway
  branch: main # Branch to update (master by default)
  squash_merges: true

# This line should *not* be indented
# publish_mode: editorial_workflow

media_folder: "img/members/" # Folder where user uploaded files should go
site_url: https://rcob3190.org/
display_url: rcob3190.org
logo_url: https://rcob3190.org/img/logo.png

collections: # A list of collections the CMS should be able to edit 
  - label: "Rotaract Club of Banashankari"
    name: "rcob"
    editor:
      preview: false
    files:
      - label: "Team | RCoB"
        name: "members"
        file: "_data/team.yml"
        fields:
          - label: Board - Team Members
            name: members
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string", default: ""}
              - {label: "Role", name: "role", widget: "string", default: ""}
              - {label: "RI ID", name: "riid", widget: "string", default: ""}
              - {label: "Image (300*400)", name: "image", widget: "image"}
          - label: Star Rotaractors
            name: stars
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string", default: ""}
              - {label: "Role", name: "role", widget: "string", default: ""}
              - {label: "RI ID", name: "riid", widget: "string", default: ""}
              - {label: "Image (300*400)", name: "image", widget: "image"}